### ISSUE TITLE
Accept an array in vhost_extra

### ISSUE THREAD

**Issue by jonhattan** [sbitio/puppet-webapp#14]
vhost_extra at present accepts a string that is passed to apache::vhost custom_fragment.

It would be nice to accept an array and internally convert it to a string.

An array allows for better templating in hiera, by using yaml anchors and hiera lookup/alias.

Example:

```yaml
# Define the general snippet to enable php fpm proxy. This snippet uses an apache defined variable for the fpmm port.
webapp__fpm : >
  <FilesMatch \.php$>
    SetHandler 'proxy:fcgi://127.0.0.1:${PHP_FPM_PORT}'
  </FilesMatch>

# Define the general structure for all instances of the "api" webapp.
# Here we set the value for the PHP_FPM_PORT before using it.
webapp__api : &api
  vhost_extra : &vhost_extra_base
    - Define PHP_FPM_PORT 9001
    - %{hiera('webapp__fpm')}

# Declare dev and prod webapps.
# In the case of prod, pick the base vhost_extra and extend with more directives. This way we avoid duplication.
webapp::instances :
  api_dev :
    <<          : *api
    servername  : 'api.dev.example.com'
    tags : 
      - dev.node.tld
  api_prod :
    <<          : *api
    servername  : 'api.example.com'
    vhost_extra :
      - *vhost_extra_base
      - php_value newrelic.appname "api.example.com"
    tags        :
      - prod.node.tld
```

Note the vhost_extra definition in api_prod produces a nested array:

```yaml
vhost_extra:
  - - Define PHP_FPM_PORT 9001
    - |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://127.0.0.1:{PHP_FPM_PORT}"
    </FilesMatch>
  - php_value newrelic.appname "api.example.com"
```

So the solution must flatten the array.

/cc @sbitio/owners
